
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.beans.PropertyChangeEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class add_agenda_panel extends javax.swing.JPanel {

    /**
     * Creates new form agenda_panel
     */
    public add_agenda_panel() {
        initComponents();
        load_event(date_picker.getDate());
        date_picker.getDateEditor().addPropertyChangeListener((PropertyChangeEvent e) -> {
            if ("date".equals(e.getPropertyName())) {
                load_event(date_picker.getDate());
                //JOptionPane.showMessageDialog(date_picker,e.getPropertyName()+ " : " + (Date) e.getNewValue());
            }
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date_picker = new com.toedter.calendar.JDateChooser();
        pan = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 51, 0));
        setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1240, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date_picker.setDate(new Date());
        date_picker.setDateFormatString("dd-MMMM-yyyy");
        date_picker.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        add(date_picker, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 190, 28));

        pan.setBackground(new Color(0, 0, 0, 0)
        );

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 1220, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date_picker;
    private javax.swing.JPanel pan;
    // End of variables declaration//GEN-END:variables

    private void load_event(Date d) {
        
        pan.removeAll();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String addDate = dateFormat.format(d);
        ArrayList<agenda> agendaList  = new ArrayList<>();
        pan.setLayout(new BoxLayout(pan, BoxLayout.X_AXIS));
        int temp=8;
        JLabel l;
        JPanel b;
        JButton btn;
        Font f=new Font("Trebuchet MS", 1, 12);
        Color transparent=new Color(0, 0, 0, 0);
        Border bordr=new EmptyBorder(10, 2, 10, 2);       
        
        for (int i = 0; i < 9; i++) {
            b = new JPanel(new BorderLayout(10,10));            
            if(i!=4){
                b.setBackground(Color.white);
                b.setAutoscrolls(true);
                agendaList = get_agenda(addDate,agendaList,temp+i);
                if (agendaList!=null ) {                    
                    DefaultListModel<String> l1 = null;
                    for(int j=0;j<agendaList.size();j++){                        
                        l1 = new DefaultListModel<>();  
                        l1.addElement(agendaList.get(j).getnom()); 
                    }
                    if(l1!=null){
                        JList<String> list = new JList<>(l1);
                        list.setBounds(100,100, 75,75); 
                        b.add(list,BorderLayout.CENTER);
                    }
                    
                }                
                l=new JLabel(Integer.toString(temp+i)+" - "+Integer.toString(temp+i+1));
                l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                l.setBackground(Color.red);
                l.setFont(f);
                l.setBorder(bordr);
                b.add(l,BorderLayout.NORTH);   
            }else{
                b.setBackground(transparent);
            }
            pan.add(b);
            pan.add(Box.createHorizontalStrut(10));
        }
        pan.revalidate();
    }
    private ArrayList<agenda> get_agenda(String d, ArrayList<agenda> a, int par){
        a.removeAll(a);
        try {            
            Statement st = ConBD.getConnection().createStatement();
            String q="select code_c,nom,prenom,type,tmp from agenda, candidat where code=code_c and jour='"+d+"' and tmp="+par+"";
            ResultSet rs = st.executeQuery(q);
            agenda b;
            while(rs.next())
            {
                b=new agenda(rs.getInt("code_c"),rs.getString("nom")+" "+rs.getString("prenom"),rs.getString("type"),rs.getInt("tmp"));
                a.add(b);
            }     
        } catch (SQLException  ex) {
            JOptionPane.showMessageDialog(pan,"ERREU :"+ex);
        }   
        return a;
    }
}
