
import java.beans.PropertyChangeEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class agenda_panel extends Gpanl {

    private final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    ArrayList<candidat> c;
    private int code=0;
    private Statement st;
    private ResultSet rs;
    
    /**
     * Creates new form NewJPanel
     */
    public agenda_panel() {
        initComponents();
        date_p.getDateEditor().addPropertyChangeListener((PropertyChangeEvent e) -> {
            if ("date".equals(e.getPropertyName())) {
                load_agenda(date_p.getDate());
                //JOptionPane.showMessageDialog(date_p,e.getPropertyName()+ " : " + (Date) e.getNewValue());
            }
        });
        load_agenda(date_p.getDate());
        load_candidat("");  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Profile = new javax.swing.JMenuItem();
        modifier = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dat_s = new com.toedter.calendar.JDateChooser();
        type = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        info = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        temp = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cherch = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        date_p = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        p10 = new javax.swing.JPanel();
        p3 = new javax.swing.JPanel();
        p11 = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        p4 = new javax.swing.JPanel();
        p8 = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        p9 = new javax.swing.JPanel();

        Profile.setText("Profile");
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfileMousePressed(evt);
            }
        });
        jPopupMenu1.add(Profile);

        modifier.setText("Modifier");
        modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifierMousePressed(evt);
            }
        });
        jPopupMenu1.add(modifier);

        setBackground(ConBD.color);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 760, 30, 10));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dat_s.setDate(new Date());
        dat_s.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(dat_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 190, 30));

        type.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code", "Creno", "Cercuit" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 90, 30));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 80, 30));

        info.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 350, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Heur :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 40, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Type :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 50, 30));

        temp.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        temp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "13", "14", "15", "16" }));
        temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempActionPerformed(evt);
            }
        });
        jPanel1.add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 90, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 40, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 1060, 80));

        cherch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cherch.setForeground(new java.awt.Color(0, 0, 51));
        cherch.setToolTipText("");
        cherch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cherchKeyReleased(evt);
            }
        });
        add(cherch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 520, 40));

        tabl.setAutoCreateRowSorter(true);
        tabl.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tabl.setForeground(new java.awt.Color(0, 0, 51));
        tabl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOM", "PRENOM", "DATE NAISSENCE", "LIEU NAISSENCE", "GENRE", "GROUPAGE", "DATE INCRIPTION", "TELEPHONE", "ADDRESSE", "TYPE PERMIS", "ETAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabl.setRowHeight(20);
        tabl.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tabl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(tabl);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1320, 410));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agenda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 24), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date_p.setDate(new Date());
        date_p.setDateFormatString("d MMMM yyyy");
        date_p.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel3.add(date_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 240, 30));

        jPanel4.setBackground(new java.awt.Color(224, 233, 246));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("8 h 00");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 162, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("9 h 00");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 162, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("10 h 00");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 162, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("11 h 00");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 162, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("13 h 00");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 162, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("14 h 00");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 162, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("15 h 00");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 162, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("16 h 00");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 162, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1282, 30));

        p10.setBackground(new java.awt.Color(255, 255, 255));
        p10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p10.setAutoscrolls(true);
        p10.setLayout(new javax.swing.BoxLayout(p10, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 161, 250));

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p3.setAutoscrolls(true);
        p3.setLayout(new javax.swing.BoxLayout(p3, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 161, 250));

        p11.setBackground(new java.awt.Color(255, 255, 255));
        p11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p11.setAutoscrolls(true);
        p11.setLayout(new javax.swing.BoxLayout(p11, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 161, 250));

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1.setAutoscrolls(true);
        p1.setLayout(new javax.swing.BoxLayout(p1, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 161, 250));

        p4.setBackground(new java.awt.Color(255, 255, 255));
        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p4.setAutoscrolls(true);
        p4.setLayout(new javax.swing.BoxLayout(p4, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 110, 161, 250));

        p8.setBackground(new java.awt.Color(255, 255, 255));
        p8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p8.setAutoscrolls(true);
        p8.setLayout(new javax.swing.BoxLayout(p8, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 161, 250));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2.setAutoscrolls(true);
        p2.setLayout(new javax.swing.BoxLayout(p2, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 161, 250));

        p9.setBackground(new java.awt.Color(255, 255, 255));
        p9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p9.setAutoscrolls(true);
        p9.setLayout(new javax.swing.BoxLayout(p9, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 161, 250));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1300, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMousePressed
        
    }//GEN-LAST:event_ProfileMousePressed

    private void modifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifierMousePressed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        add_agenda();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempActionPerformed

    private void cherchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cherchKeyReleased
        load_candidat(cherch.getText());
    }//GEN-LAST:event_cherchKeyReleased

    private void tablMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablMousePressed
        display_info(tabl.getSelectedRow());
    }//GEN-LAST:event_tablMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Profile;
    private javax.swing.JTextField cherch;
    private com.toedter.calendar.JDateChooser dat_s;
    private com.toedter.calendar.JDateChooser date_p;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JMenuItem modifier;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p10;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p8;
    private javax.swing.JPanel p9;
    private javax.swing.JTable tabl;
    private javax.swing.JComboBox<String> temp;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables

   

        private void load_candidat(String string) {
        DefaultTableModel model = (DefaultTableModel)tabl.getModel();
        c=get_candidat(string);
        model.setRowCount(0);
        Object[] row = new Object[11];
        for(int i = 0; i < c.size(); i++)
        {
            row[0] = c.get(i).getNOM();
            row[1] = c.get(i).getPrenom();
            row[2] = c.get(i).getDate_n();
            row[3] = c.get(i).getLieu();
            row[4] = c.get(i).getgenre();
            row[5] = c.get(i).getGroupage();
            row[6] = c.get(i).getDate_i();
            row[7] = c.get(i).getTél();
            row[8] = c.get(i).getadress();
            row[9] = c.get(i).gettype();
            row[10] = c.get(i).getetat();
            model.addRow(row);
        }
    }
    private ArrayList<candidat> get_candidat(String d){
        ArrayList<candidat> c1=new ArrayList<>();
        try {            
            String q;
            if("".equals(d)) q="select * from candidat order by date_inscri desc";
            else q="select * from candidat where nom like '%"+d+"%' or prenom like '%"+d+"%' order by date_inscri desc";
            rs = request(q);
            candidat b;
            while(rs.next())
            {
                b=new candidat(rs.getInt("code"),rs.getString("nom"),rs.getString("prenom"),rs.getDate("date_n"),rs.getString("lieu_n"),rs.getString("groupage"),rs.getString("sexe"),rs.getString("tel"), rs.getString("adress"),rs.getDate("date_inscri"),rs.getString("type_p"),rs.getString("etat"),null);
                c1.add(b);
            }          
        } catch (SQLException  ex) {
            JOptionPane.showMessageDialog(jPanel1,"ERREU :"+ex);
        }   
        return c1;
    }

    private void display_info(int i) {
        code=c.get(i).getCode();
        info.setText(c.get(i).getNOM()+" "+c.get(i).getPrenom());
    }
    private void add_agenda(){
        if(code!=0 && check()==0){
            String UpdateQuery = "INSERT INTO `agenda`(code_c, jour, tmp, type) VALUES ("+code+",'"+dateFormat.format(dat_s.getDate())+"','"+temp.getSelectedItem()+"','"+type.getSelectedItem()+"')";
            update(UpdateQuery);
            load_candidat("");
            clear();
            JOptionPane.showMessageDialog(null, "Ajouter");
            load_agenda(date_p.getDate());  
        }
    }

    private int check() {
        String q="select * from agenda where code_c="+code+" and jour='"+dateFormat.format(dat_s.getDate())+"' and tmp="+temp.getSelectedItem();
        try {
            return request(q).getFetchSize();
        } catch (SQLException ex) {
            return 1;
        }
    }

    private void clear() {
        info.setText("");
        code=0;
        dat_s.setDate(new Date());
        type.setSelectedIndex(0);
        temp.setSelectedIndex(0);
    }
    private ResultSet request(String q) {
        try {            
            st = ConBD.getConnection().createStatement();
            return st.executeQuery(q);
        } catch (SQLException  ex) {
            JOptionPane.showMessageDialog(info,"ERREU :"+ex);
        }   
        return null;
    }
    private void update(String q){
        try {
                PreparedStatement ps = ConBD.getConnection().prepareStatement(q);
                ps.executeUpdate();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(info, e);
            }   
    }

    private void load_agenda(Date date) {

        p1.removeAll();
        p2.removeAll();
        p3.removeAll();
        p4.removeAll();
        p8.removeAll();
        p9.removeAll();
        p10.removeAll();
        p11.removeAll();
        get_agenda2(dateFormat.format(date));
        p1.revalidate();
        p1.repaint();
        p2.revalidate();
        p2.repaint();
        p3.revalidate();
        p3.repaint();
        p4.revalidate();
        p4.repaint();
        p8.revalidate();
        p8.repaint();
        p9.revalidate();
        p9.repaint();
        p10.revalidate();
        p10.repaint();
        p11.revalidate();
        p11.repaint();
    }
    private void add_to_pan(String nom,int tem){
        switch(tem){
            case 8:p8.add(new JLabel(nom));
                   break;
            case 9:p9.add(new JLabel(nom));
                   break;
            case 10:p10.add(new JLabel(nom));
                   break;   
            case 11:p11.add(new JLabel(nom));
                   break;
            case 13:p1.add(new JLabel(nom));
                   break;
            case 14:p2.add(new JLabel(nom));
                   break;
            case 15:p3.add(new JLabel(nom));
                   break;   
            case 16:p4.add(new JLabel(nom));
                   break;
        }
            
    }

    private void get_agenda2(String format) {
        try {            
            rs = request("select code_c,nom,prenom,type,tmp from agenda, candidat where code=code_c and jour='"+format+"'");
            //System.out.println("select code_c,nom,prenom,type,tmp from agenda, candidat where code=code_c and jour='"+format+"'");
            agenda b;
            while(rs.next())
            {
                add_to_pan(rs.getString("nom")+" "+rs.getString("prenom"), rs.getInt("tmp"));
            }     
        } catch (SQLException  ex) {
            JOptionPane.showMessageDialog(null,"ERREU :"+ex);
        }   
    }
}


