


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class agenda_panel extends javax.swing.JPanel {

    /**
     * Creates new form agenda_panel
     */
    public agenda_panel() {
        initComponents();
        pan_inside.add(new add_agenda_panel());
        pan_inside.add(new add_agenda_panel1());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        pan_inside = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 51, 0));
        setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_inside.setBackground(new java.awt.Color(153, 51, 0));
        pan_inside.setLayout(new java.awt.GridLayout(2, 1));
        scroll.setViewportView(pan_inside);

        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pan_inside;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

}
