
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class candidat_panel extends javax.swing.JPanel {
    
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    ArrayList<candidat> c;
    /**
     * Creates new form NewJPanel
     */
    public candidat_panel() {
        initComponents();
        load_candidat("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Profile = new javax.swing.JMenuItem();
        modifier = new javax.swing.JMenuItem();
        can_info_pan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date_n = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        lieu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        date_i = new com.toedter.calendar.JDateChooser();
        genr = new javax.swing.JComboBox<>();
        group = new javax.swing.JComboBox<>();
        vider = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        adress = new javax.swing.JTextField();
        type_p = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        modifer = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabl = new javax.swing.JTable();
        cherch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        Profile.setText("Profile");
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfileMousePressed(evt);
            }
        });
        jPopupMenu1.add(Profile);

        modifier.setText("Modifier");
        modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifierMousePressed(evt);
            }
        });
        jPopupMenu1.add(modifier);

        setBackground(new java.awt.Color(153, 51, 0));
        setAutoscrolls(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        can_info_pan.setBackground(new java.awt.Color(204, 204, 204));
        can_info_pan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)), "INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 14), new java.awt.Color(102, 0, 0))); // NOI18N
        can_info_pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("NOM :");
        jLabel1.setToolTipText("");
        can_info_pan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 30));

        nom.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        nom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        can_info_pan.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 180, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("PRENOM :");
        jLabel2.setToolTipText("");
        can_info_pan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, 30));

        prenom.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        prenom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        can_info_pan.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("DATE NAISSANCE :");
        jLabel3.setToolTipText("");
        can_info_pan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 110, 30));

        date_n.setDate(new Date());
        date_n.setDateFormatString("dd-MM-yyyy");
        date_n.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        can_info_pan.add(date_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 180, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 102));
        jLabel4.setText("LIEU NAISSENCE :");
        jLabel4.setToolTipText("");
        can_info_pan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 110, 30));

        lieu.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        can_info_pan.add(lieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 180, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("GROUPAGE :");
        jLabel5.setToolTipText("");
        can_info_pan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 70, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 102));
        jLabel6.setText("TYPE PERMI :");
        jLabel6.setToolTipText("");
        can_info_pan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 80, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 102));
        jLabel7.setText("TELEPHONE :");
        jLabel7.setToolTipText("");
        can_info_pan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 80, 30));

        tel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        can_info_pan.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 180, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 102));
        jLabel8.setText("DATE INSCRIT :");
        jLabel8.setToolTipText("");
        can_info_pan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 90, 30));

        date_i.setDate(new Date());
        date_i.setDateFormatString("dd-MM-yyyy");
        date_i.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        can_info_pan.add(date_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 180, 30));

        genr.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        genr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOMME", "FEMME" }));
        can_info_pan.add(genr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 90, 30));

        group.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "AB+", "AB-", "B+", "B-", "O+", "O-" }));
        can_info_pan.add(group, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 90, 30));

        vider.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
        vider.setForeground(new java.awt.Color(0, 0, 51));
        vider.setText("VIDER");
        vider.setToolTipText("");
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });
        can_info_pan.add(vider, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 120, 30));

        ajouter.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
        ajouter.setForeground(new java.awt.Color(0, 0, 51));
        ajouter.setText("AJOUTER");
        ajouter.setToolTipText("");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        can_info_pan.add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 120, 30));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 102));
        jLabel14.setText("ADRESS *:");
        jLabel14.setToolTipText("");
        can_info_pan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 60, 30));

        adress.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        adress.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressActionPerformed(evt);
            }
        });
        can_info_pan.add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 180, 30));

        type_p.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        type_p.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C1", "C2", "C3" }));
        can_info_pan.add(type_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 90, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("GENRE :");
        jLabel10.setToolTipText("");
        can_info_pan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 60, 30));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        can_info_pan.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 110, 110));

        modifer.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
        modifer.setForeground(new java.awt.Color(0, 0, 51));
        modifer.setText("Modifier");
        modifer.setToolTipText("");
        modifer.setEnabled(false);
        modifer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modiferActionPerformed(evt);
            }
        });
        can_info_pan.add(modifer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 120, 30));

        add(can_info_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 1230, 170));

        tabl.setAutoCreateRowSorter(true);
        tabl.setBackground(new java.awt.Color(204, 204, 204));
        tabl.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tabl.setForeground(new java.awt.Color(0, 0, 51));
        tabl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOM", "PRENOM", "DATE NAISSENCE", "LIEU NAISSENCE", "GENRE", "GROUPAGE", "DATE INCRIPTION", "TELEPHONE", "ADDRESSE", "TYPE PERMIS", "ETAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabl.setComponentPopupMenu(jPopupMenu1);
        tabl.setSelectionBackground(new java.awt.Color(241, 179, 205));
        tabl.setSelectionForeground(new java.awt.Color(102, 0, 0));
        jScrollPane6.setViewportView(tabl);
        if (tabl.getColumnModel().getColumnCount() > 0) {
            tabl.getColumnModel().getColumn(0).setResizable(false);
            tabl.getColumnModel().getColumn(1).setResizable(false);
            tabl.getColumnModel().getColumn(2).setResizable(false);
            tabl.getColumnModel().getColumn(3).setResizable(false);
            tabl.getColumnModel().getColumn(4).setResizable(false);
            tabl.getColumnModel().getColumn(4).setPreferredWidth(30);
            tabl.getColumnModel().getColumn(5).setResizable(false);
            tabl.getColumnModel().getColumn(5).setPreferredWidth(40);
            tabl.getColumnModel().getColumn(6).setResizable(false);
            tabl.getColumnModel().getColumn(7).setResizable(false);
            tabl.getColumnModel().getColumn(8).setResizable(false);
            tabl.getColumnModel().getColumn(9).setResizable(false);
            tabl.getColumnModel().getColumn(9).setPreferredWidth(60);
            tabl.getColumnModel().getColumn(10).setResizable(false);
            tabl.getColumnModel().getColumn(10).setPreferredWidth(50);
        }

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 1290, 370));

        cherch.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cherch.setForeground(new java.awt.Color(0, 0, 51));
        cherch.setToolTipText("");
        cherch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cherchKeyReleased(evt);
            }
        });
        add(cherch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 520, 40));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 650, 30, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        vider();
    }//GEN-LAST:event_viderActionPerformed

    private void adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressActionPerformed

    private void ProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMousePressed
        JOptionPane.showMessageDialog(can_info_pan, evt);
    }//GEN-LAST:event_ProfileMousePressed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        insert_candidat();
    }//GEN-LAST:event_ajouterActionPerformed

    private void cherchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cherchKeyReleased
        load_candidat(cherch.getText());
    }//GEN-LAST:event_cherchKeyReleased

    private void modiferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modiferActionPerformed
       modifier();
    }//GEN-LAST:event_modiferActionPerformed

    private void modifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMousePressed
        //remplir(evt.getComponent().);
    }//GEN-LAST:event_modifierMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Profile;
    private javax.swing.JTextField adress;
    private javax.swing.JButton ajouter;
    private javax.swing.JPanel can_info_pan;
    private javax.swing.JTextField cherch;
    private com.toedter.calendar.JDateChooser date_i;
    private com.toedter.calendar.JDateChooser date_n;
    private javax.swing.JComboBox<String> genr;
    private javax.swing.JComboBox<String> group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField lieu;
    private javax.swing.JButton modifer;
    private javax.swing.JMenuItem modifier;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTable tabl;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<String> type_p;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables

    private void load_candidat(String string) {
        DefaultTableModel model = (DefaultTableModel)tabl.getModel();
        c=get_candidat(string);
        model.setRowCount(0);
        Object[] row = new Object[10];
        for(int i = 0; i < c.size(); i++)
        {
            row[0] = c.get(i).getNOM();
            row[1] = c.get(i).getPrenom();
            row[2] = c.get(i).getDate_n();
            row[3] = c.get(i).getLieu();
            row[4] = c.get(i).getgenre();
            row[5] = c.get(i).getGroupage();
            row[6] = c.get(i).getDate_i();
            row[7] = c.get(i).getTél();
            row[8] = c.get(i).getadress();
            row[9] = c.get(i).gettype();
            
            model.addRow(row);
        }
    }
    private ArrayList<candidat> get_candidat(String d){
        ArrayList<candidat> c1=new ArrayList<>();
        try {            
            Statement st = ConBD.getConnection().createStatement();
            String q;
            if("".equals(d)) q="select * from candidat order by date_inscri desc";
            else q="select * from candidat where nom like '%"+d+"%' or prenom like '%"+d+"%' order by date_inscri desc";
            ResultSet rs = st.executeQuery(q);
            candidat b;
            while(rs.next())
            {
                b=new candidat(rs.getInt("code"),rs.getString("nom"),rs.getString("prenom"),rs.getDate("date_n"),rs.getString("lieu_n"),rs.getString("groupage"),rs.getString("sexe"),rs.getString("tel"), rs.getString("adress"),rs.getDate("date_inscri"),rs.getString("type_p"),rs.getString("etat"));
                c1.add(b);
            }     
        } catch (SQLException  ex) {
            JOptionPane.showMessageDialog(can_info_pan,"ERREU :"+ex);
        }   
        return c1;
    }

    private void insert_candidat() {
        if(check1() && check2()==0){
            try {
                String UpdateQuery = "INSERT INTO `candidat`(`nom`, `prenom`, `date_n`, `lieu_n`, `groupage`, `sexe`, `tel`, `date_inscri`, `type_p`, `adress`) VALUES (?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement ps = ConBD.getConnection().prepareStatement(UpdateQuery);
                ps.setString(1,nom.getText());
                ps.setString(2,prenom.getText());
                ps.setString(3,dateFormat.format(date_n.getDate()));
                ps.setString(4,lieu.getText());
                ps.setString(5, (String) group.getSelectedItem());
                ps.setString(6, (String) genr.getSelectedItem());
                ps.setString(7,tel.getText());
                ps.setString(8, dateFormat.format(date_i.getDate()));
                ps.setString(9, (String) type_p.getSelectedItem());
                ps.setString(10,adress.getText());
                ps.executeUpdate();
                load_candidat("");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(can_info_pan, e);
            }    
        }else JOptionPane.showMessageDialog(can_info_pan, "Veiller veriler les information");
    }

    private void vider() {
        nom.setText(""); 
        prenom.setText("");
        lieu.setText("");
        adress.setText("");
        tel.setText("");
        date_i.cleanup();
        date_n.cleanup();
        group.setSelectedIndex(0);
        genr.setSelectedIndex(0);
        type_p.setSelectedIndex(0);
        date_i.setDate(new Date());
        date_n.setDate(new Date());
        ajouter.setEnabled(true);
        modifer.setEnabled(false);
    }

    private boolean check1() {
        return !(nom.getText().equals("") || prenom.getText().equals("") || lieu.getText().equals("") || adress.getText().equals("") || tel.getText().equals("") || date_i.getDate().equals("") || date_n.getDate().equals(""));
    }

    private int check2() {
        try {            
            Statement st = ConBD.getConnection().createStatement();
            String q="select * from candidat where nom='"+nom.getText()+"%' and prenom='"+prenom.getText()+"%' and date_n='"+dateFormat.format(date_n.getDate())+"' and lieu_n='"+lieu.getText()+"' and groupage='"+group.getSelectedItem()+"' and sexe='"+genr.getSelectedItem()+"' and type_p='"+type_p.getSelectedItem()+"'";
            System.out.println(q);
            ResultSet rs = st.executeQuery(q);
            System.out.println("count "+rs.getFetchSize());
            return rs.getFetchSize();
        } catch (SQLException  ex) {
            JOptionPane.showMessageDialog(can_info_pan,"ERREU :"+ex);
        }   
        return 0;
    }

    private void modifier() {
       
    }

    private void remplir() {
        
    }
}
