
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Box;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class main_fram extends javax.swing.JFrame {
    private final utilisateur u;
    /**
     * Creates new form main_fram
     * @param u
     * @param n
     */
    public main_fram(utilisateur u,int n) {
        initComponents();
        jMenuBar1.add(Box.createGlue());
        jMenuBar1.add(jMenu5);
        jMenuBar1.add(jMenu3);
        this.u=u;
        change_panel(n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        agenda = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(panel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        agenda.setText("Agenda");
        agenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agendaMousePressed(evt);
            }
        });
        jMenuBar1.add(agenda);

        jMenu1.setText("Candidat");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Examen");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Parametre");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu3.setText("X");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu5.setText("_");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1355, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        deconnect();
    }//GEN-LAST:event_jMenu3MousePressed

    private void agendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendaMousePressed
        main_fram f=new main_fram(u,1);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agendaMousePressed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        main_fram f=new main_fram(u,2);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        main_fram f=new main_fram(u,3);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        main_fram f=new main_fram(u,4);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu4MousePressed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
        this.setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_jMenu5MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu agenda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    
    private void deconnect() {
        try { 
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String Query = "INSERT INTO `connections`(`user`,`etat`,date_c) VALUES ("+u.getID()+",0,?)";
            PreparedStatement ps = ConBD.getConnection().prepareStatement(Query);
            ps.setString(1,dateFormat.format(new Date()));
            ps.executeUpdate();
            System.exit(0);            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }  
    }
    private void change_panel(int n){
        switch(n){
            case 1:panel.removeAll();
                panel.add(new agenda_panel());
                break;
            case 2:panel.removeAll();
                panel.add(new candidat_panel());
                break;
            case 3:panel.removeAll();
                panel.add(new examen_panel());
                break;
            case 4:panel.removeAll();
                panel.add(new parametre());
                break;
       }
    }
    
}
