/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class parametre extends Gpanl {

    /**
     * Creates new form parametre
     */
    public parametre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nom11 = new javax.swing.JLabel();
        nom1 = new javax.swing.JLabel();
        nom2 = new javax.swing.JLabel();
        nom3 = new javax.swing.JLabel();
        nom4 = new javax.swing.JLabel();
        nom5 = new javax.swing.JLabel();
        nom6 = new javax.swing.JLabel();
        nom7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        comun = new javax.swing.JTextField();
        daira = new javax.swing.JTextField();
        wilaya = new javax.swing.JTextField();
        adr = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        n_ecol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nom11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nom11.setForeground(new java.awt.Color(51, 0, 102));
        nom11.setText("Telephone :");
        nom11.setToolTipText("");
        jPanel1.add(nom11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 30));

        nom1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nom1.setForeground(new java.awt.Color(51, 0, 102));
        nom1.setText("Nom ecole :");
        nom1.setToolTipText("");
        jPanel1.add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 30));

        nom2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nom2.setForeground(new java.awt.Color(51, 0, 102));
        nom2.setText("Nom Responsable :");
        nom2.setToolTipText("");
        jPanel1.add(nom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 30));

        nom3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nom3.setForeground(new java.awt.Color(51, 0, 102));
        nom3.setText("Prenom Responsable :");
        nom3.setToolTipText("");
        jPanel1.add(nom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 30));

        nom4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nom4.setForeground(new java.awt.Color(51, 0, 102));
        nom4.setText("Comune :");
        nom4.setToolTipText("");
        jPanel1.add(nom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 30));

        nom5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nom5.setForeground(new java.awt.Color(51, 0, 102));
        nom5.setText("Daira :");
        nom5.setToolTipText("");
        jPanel1.add(nom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 30));

        nom6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nom6.setForeground(new java.awt.Color(51, 0, 102));
        nom6.setText("Wilaya :");
        nom6.setToolTipText("");
        jPanel1.add(nom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 30));

        nom7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nom7.setForeground(new java.awt.Color(51, 0, 102));
        nom7.setText("Adress :");
        nom7.setToolTipText("");
        jPanel1.add(nom7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, 30));

        nom.setBackground(new java.awt.Color(204, 204, 204));
        nom.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 200, 30));

        prenom.setBackground(new java.awt.Color(204, 204, 204));
        prenom.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, 30));

        comun.setBackground(new java.awt.Color(204, 204, 204));
        comun.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(comun, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 200, 30));

        daira.setBackground(new java.awt.Color(204, 204, 204));
        daira.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(daira, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, 30));

        wilaya.setBackground(new java.awt.Color(204, 204, 204));
        wilaya.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(wilaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 200, 30));

        adr.setBackground(new java.awt.Color(204, 204, 204));
        adr.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(adr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 200, 30));

        tel.setBackground(new java.awt.Color(204, 204, 204));
        tel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 200, 30));

        n_ecol.setBackground(new java.awt.Color(204, 204, 204));
        n_ecol.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(n_ecol, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 200, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 420, 430));

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nom", "Prenom", "Date", "Etat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 40, 830, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adr;
    private javax.swing.JTextField comun;
    private javax.swing.JTextField daira;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField n_ecol;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel nom1;
    private javax.swing.JLabel nom11;
    private javax.swing.JLabel nom2;
    private javax.swing.JLabel nom3;
    private javax.swing.JLabel nom4;
    private javax.swing.JLabel nom5;
    private javax.swing.JLabel nom6;
    private javax.swing.JLabel nom7;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField wilaya;
    // End of variables declaration//GEN-END:variables
}
