
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
        
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHADOW
 */
public class r_examen extends javax.swing.JFrame {

    private int id;
    private ArrayList<examen> examens;
    /**
     * Creates new form NewJFrame
     * @param nom
     * @param id
     */
    public r_examen(String nom,int id) {
        initComponents();
        typ.setText(nom);
        this.id=id;
        load_candidat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Gpanl();
        typ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        disp = new javax.swing.JLabel();
        stat = new javax.swing.JComboBox<>();
        eta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        obs = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Examen");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typ.setBackground(new java.awt.Color(255, 255, 255));
        typ.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        typ.setForeground(new java.awt.Color(0, 0, 102));
        typ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typ.setText("info");
        jPanel1.add(typ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 670, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom ", "Prenom", "Dte inscription ", "Telephone", "Etat", "Resultat", "Observation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(20);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1210, 350));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 95, 30));

        disp.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        disp.setForeground(new java.awt.Color(0, 0, 102));
        disp.setText("Resultat :");
        jPanel2.add(disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 30));

        stat.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        stat.setForeground(new java.awt.Color(0, 0, 102));
        stat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PASSER", "RATER" }));
        stat.setPreferredSize(new java.awt.Dimension(61, 20));
        jPanel2.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 110, 30));

        eta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        eta.setForeground(new java.awt.Color(0, 0, 102));
        eta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CODE", "CRENO", "CERCUIT", "FINI" }));
        eta.setPreferredSize(new java.awt.Dimension(67, 20));
        jPanel2.add(eta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Observation :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 80, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Etat :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 40, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Resultat :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 60, 30));

        obs.setColumns(20);
        obs.setRows(2);
        jScrollPane3.setViewportView(obs);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 250, 70));

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 95, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 1030, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1266, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
        disp.setText(examens.get(table.getSelectedRow()).getnom()+" "+examens.get(table.getSelectedRow()).getprenom());
        obs.setText(examens.get(table.getSelectedRow()).getobs());
        stat.setSelectedItem(examens.get(table.getSelectedRow()).getstatu());
        eta.setSelectedItem(examens.get(table.getSelectedRow()).getetat());
    }//GEN-LAST:event_tableMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        update("update pass set statu=upper('"+stat.getSelectedItem()+"') ,obs=upper('"+obs.getText()+"') where id="+id+" and code="+examens.get(table.getSelectedRow()).getcode());
        update("update candidat set etat=upper('"+eta.getSelectedItem()+"') where code="+examens.get(table.getSelectedRow()).getcode());
        load_candidat();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disp;
    private javax.swing.JComboBox<String> eta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea obs;
    private javax.swing.JComboBox<String> stat;
    private javax.swing.JTable table;
    private javax.swing.JLabel typ;
    // End of variables declaration//GEN-END:variables
    private ResultSet request(String q1){
        try {            
            Statement st = ConBD.getConnection().createStatement();
            return st.executeQuery(q1);
        } catch (SQLException  ex) {
            JOptionPane.showMessageDialog(null,"ERREU :"+ex);
            return null;
        }   
    }
    private void update(String q){
        try {
            PreparedStatement ps = ConBD.getConnection().prepareStatement(q);
                ps.executeUpdate();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }

    private void load_candidat() {
        String q = "select c.code,nom,prenom,tel,date_inscri,etat,obs,statu from pass p,candidat c where id="+id+" and p.code=c.code order by nom desc";
        ResultSet rs = request(q);
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        model.setRowCount(0);
        Object[] row = new Object[7];
        examens=new ArrayList<>();
        try {
            while(rs.next())
            {
                examens.add(new examen(rs.getInt("code"), rs.getString("nom"), rs.getString("prenom"), rs.getString("date_inscri"), rs.getString("etat"), rs.getString("statu"), rs.getString("obs"), rs.getString("tel")));
                row[0] = rs.getString("nom");
                row[1] = rs.getString("prenom");
                row[2] = rs.getString("date_inscri");
                row[3] = rs.getString("tel");
                row[4] = rs.getString("etat");
                row[5] = rs.getString("statu");
                row[6] = rs.getString("obs");
                model.addRow(row);   
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex );
        }
    }

}
